# Generated by Django 2.2.4 on 2019-08-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComprarCredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=3, max_digits=11)),
                ('qtd_parcela', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('codigo_trasacao', models.CharField(blank=True, default='0', max_length=80, null=True)),
                ('statu_trasacao', models.CharField(blank=True, max_length=300, null=True)),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-data_compra',),
            },
        ),
    ]
