# Generated by Django 2.2.4 on 2019-08-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComprarCredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_compra', models.PositiveIntegerField(blank=True, default=10, null=True)),
                ('cliente', models.CharField(blank=True, max_length=80, null=True)),
                ('numero_cartao', models.CharField(blank=True, max_length=50, null=True)),
                ('seguranca', models.CharField(blank=True, max_length=10, null=True)),
                ('bandeira', models.CharField(choices=[('Visa', 'Visa'), ('Master', 'Master'), ('Hipercard', 'Hipercard'), ('Hiper', 'Hiper'), ('American Express', 'American Express'), ('Elo', 'Elo'), ('Diners Club', 'Diners Club'), ('American Express', 'American Express'), ('Discover', 'Discover'), ('JCB', 'JCB'), ('Aura', 'Aura')], max_length=80)),
                ('validade', models.CharField(blank=True, max_length=8, null=True)),
                ('valor', models.PositiveIntegerField(blank=True, default=100, null=True)),
                ('qtd_parcela', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('codigo_trasacao', models.CharField(blank=True, default='0', max_length=80, null=True)),
                ('statu_trasacao', models.CharField(blank=True, max_length=300, null=True)),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-data_compra',),
            },
        ),
    ]
