# Generated by Django 2.2.4 on 2019-08-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cielo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprarcredito',
            name='bandeira',
            field=models.CharField(choices=[('Visa', 'Visa'), ('Master', 'Master'), ('Hipercard', 'Hipercard'), ('Hiper', 'Hiper'), ('American Express', 'American Express'), ('Elo', 'Elo'), ('Diners Club', 'Diners Club'), ('American Express', 'American Express'), ('Discover', 'Discover'), ('JCB', 'JCB'), ('Aura', 'Aura')], default='Visa', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comprarcredito',
            name='cliente',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='comprarcredito',
            name='id_compra',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='comprarcredito',
            name='numero_cartao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='comprarcredito',
            name='seguranca',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='comprarcredito',
            name='validade',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='comprarcredito',
            name='valor',
            field=models.PositiveIntegerField(blank=True, default=100, null=True),
        ),
    ]
